import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google"


export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'TEST FOLDER 222',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <>
   {children}
   </>
  )
}
